# =========================================================
# APPLICATION
# =========================================================
spring.application.name=ev-battery-health

# =========================================================
# POSTGRESQL DATABASE
# =========================================================
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/EVCharging}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Prateek@123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# =========================================================
# JPA / HIBERNATE
# =========================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================================================
# SERVER
# =========================================================
server.port=${PORT:8080}

# =========================================================
# EUREKA
# =========================================================
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false