spring.application.name=ev-battery-health

spring.datasource.url=jdbc:postgresql://localhost:5432/EVCharging
spring.datasource.username=postgres
spring.datasource.password=Prateek@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Eureka client config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# Enable client registration (will print warning but start successfully if Eureka is not running)
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

server.port=8080

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=prateek2222kumar@gmail.com
spring.mail.password=wvmb nvwo grqz ervh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

