# =========================================================
# APPLICATION
# =========================================================

spring.application.name=ev-battery-health


# =========================================================
# POSTGRESQL DATABASE - RENDER
# =========================================================

spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver


# =========================================================
# HIKARI CONNECTION POOL
# =========================================================

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000


# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# =========================================================
# SERVER
# =========================================================

server.port=${PORT:8080}


# =========================================================
# EUREKA - DISABLED FOR RENDER
# =========================================================

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false